spring.application.name=ecommerce-multivendor

server.port=5454
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${url}
spring.datasource.username=${username}
spring.datasource.password=${password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

mailjet.api.key=${MAILJET_API_KEY}
mailjet.api.secret=${MAILJET_API_SECRET}
mail.from=${MAIL_FROM}

stripe.api.key=YOUR_STRIPE_SECRET_KEY

razorpay.api.key=${RAZORPAY_API_KEY}
razorpay.api.secret=${RAZORPAY_API_SECRET}
