spring.application.name=ecommerce-multivendor

server.port=5454
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${url}
spring.datasource.username=${username}
spring.datasource.password=${password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=revathibakkiyaraj49@gmail.com
spring.mail.password=qprt guwn ocmo kkmq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

stripe.api.key=YOUR_STRIPE_SECRET_KEY

razorpay.api.key=rzp_test_TQpA8iKA8Eom0c
razorpay.api.secret=HjNhzZmwtSCxemK6ZLUxP9E9
